### PR TITLE
Data Validation phase completed

### LINKED ISSUE #4: Data Validation
Validate the data

### PR DESCRIPTION
**Pull request by ASM313**
### Data Validation completed

- No. of columns validated
- Data drift report in report.yaml

### CODE REVIEW

**Comment by ASM313** [comment]
This fixes #4

**Comment by Atiq-Ur-Rehman7** [comment]
Ok, continue monitoring the drifts in data.

**Comment by Atiq-Ur-Rehman7** [comment]
In future amount of data will increase.

**Comment by ASM313** [comment]
Setup is ready for large amount of data.

**Pull request merged**
